FROM alpine:3.20

RUN apk add --no-cache netcat-openbsd

WORKDIR /forwarder

COPY scripts/forward-zeek.sh /usr/local/bin/forward-zeek.sh
RUN chmod +x /usr/local/bin/forward-zeek.sh

ENTRYPOINT ["/usr/local/bin/forward-zeek.sh"]