#!/usr/bin/env python3
"""Create multiple concurrent TheHive case creation requests."""

from __future__ import annotations

import argparse
import concurrent.futures as futures
import json
import os
import ssl
import time
import urllib.request
from dataclasses import dataclass


@dataclass(frozen=True)
class Result:
    ok: bool
    elapsed: float
    payload: str


def post_json(url: str, api_key: str, payload: dict, insecure: bool = True) -> Result:
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": api_key,
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
        method="POST",
    )
    context = ssl._create_unverified_context() if insecure else None
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(request, context=context) as response:
            body = response.read().decode("utf-8")
        return Result(True, time.perf_counter() - started, body)
    except Exception as exc:  # pragma: no cover - benchmark helper
        return Result(False, time.perf_counter() - started, str(exc))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-url", default=os.environ.get("THEHIVE_URL", "http://localhost:9000"))
    parser.add_argument("--api-key", default=os.environ.get("THEHIVE_API_KEY", ""))
    parser.add_argument("--endpoint", default=os.environ.get("THEHIVE_CASE_ENDPOINT", "/api/v1/case"))
    parser.add_argument("--count", type=int, default=100)
    parser.add_argument("--workers", type=int, default=10)
    args = parser.parse_args()

    if not args.api_key:
        raise SystemExit("TheHive API key is required via --api-key or THEHIVE_API_KEY.")

    def build_payload(index: int) -> dict:
        return {
            "title": f"Lab case {index}",
            "description": "Concurrent load test generated by perf_load.py",
            "severity": 2,
            "tags": ["lab", "load-test"],
            "flag": False,
        }

    started = time.perf_counter()
    results: list[Result] = []
    with futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
        jobs = [pool.submit(post_json, f"{args.base_url}{args.endpoint}", args.api_key, build_payload(index)) for index in range(1, args.count + 1)]
        for job in futures.as_completed(jobs):
            results.append(job.result())

    successes = sum(1 for result in results if result.ok)
    failures = len(results) - successes
    average = sum(result.elapsed for result in results) / len(results)
    print(json.dumps({"count": len(results), "successes": successes, "failures": failures, "average_seconds": round(average, 3), "total_seconds": round(time.perf_counter() - started, 3)}, indent=2))
    if failures:
        print("Some requests failed. Inspect THEHIVE_CASE_ENDPOINT and credentials.")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
