play.http.secret.key = ${?THEHIVE_SECRET}

search {
  uri = "http://elasticsearch:9200"
  username = "elastic"
  password = ${?ELASTIC_PASSWORD}
  index = "thehive"
}

storage {
  backend = "fs"
  fs {
    location = "/opt/thehive/files"
  }
}

play.modules.enabled += org.thp.thehive.connector.misp.MispModule

misp {
  servers = [
    {
      name = "local"
      url = "http://misp-core"
      auth {
        type = "bearer"
        key = ${?MISP_API_KEY}
      }
      wsConfig {
        ssl {
          loose {
            acceptAnyCertificate = true
          }
        }
      }
      sync {
        interval = 5m
        scoreThreshold = 50
        maxResults = 50
      }
    }
  ]
}

alert {
  import {
    enabled = true
    schedule = "*/5 * * * *"
    tags = ["misp", "lab"]
    severity = "high"
  }
}

notification.webhook.endpoints = [
  {
    name = "local-webhook"
    url = "http://thehive:9000/api/webhook/lab"
    version = 0
    wsConfig = {}
    includedTheHiveOrganisations = []
    excludedTheHiveOrganisations = []
  }
]
